# Server details
server:
  port: 8443
  
# SEC Links
sec:
  urls:
    sic-codes: https://www.sec.gov/info/edgar/siccodes.htm
    ciks: https://www.sec.gov/files/company_tickers.json
    company-details: 
      prefix: https://www.edgarcompany.sec.gov/servlet/CompanyDBSearch?page=detailed&cik=
      suffix: "&main_back=2"
  local-folders:
    ciks: /tmp/company_tickers.json
    
# Swagger documentation
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    
# Batch size for database operations    
database:
  batchSize:
    inserts: 500
    
# Spring Data Sources
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financial-data
    username: admin
    password: admin
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
        type: trace
        use_sql_comments: false
        default_schema: ticker_list
    show-sql: false